site_name: ZJUCSSU
site_url: https://ZJUCSSU.github.io/home/
repo_url: https://github.com/ZJUCSSU/home/
repo_name: ZJUCSSU/home
site_description: Welcome to ZJUCSSU
site_author: ZJUCSSU
copyright: Copyright &copy; 2024 ZJUCSSU

markdown_extensions:
  # === 从这里开始到下面，是 pymdown-extensions 库的 markdown_extensions 配置 ===

  - pymdownx.keys # 按键高亮，类似于行内代码那种，如 <kbd>Ctrl</kbd>，或者带图标的格式（强制小写）++ctrl++，也可组合 ++ctrl+s++（推荐第二种方式，第二种自带图标）
  - pymdownx.mark # 允许文本下划线，即 ^^Text^^
  - pymdownx.caret # 允许文本高亮，即 ==Text==
  - pymdownx.tilde # 允许文本删除线，即 ~~Text~~
  - pymdownx.details # 允许提示框与文本左右布局，而非原来的上下布局，如 !!! note inline "Hint"（左），!!! note inline end（右）
  - pymdownx.snippets # 允许外联任何内容
  - pymdownx.striphtml # 去除 HTML 中不需要的注释和 / 或标记属性，可减小 HTML 大小
  - pymdownx.smartsymbols # 允许上下标，如 x^2^（x²）
  - pymdownx.inlinehilite # 支持行内代码块高亮，如 `#!python range()`
  - pymdownx.smartsymbols # 智能符号，如 (c) 就是 ©️

  - pymdownx.b64 # 允许使用 base64 编码嵌入本地 PNG、JPEG 和 GIF 图像引用（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.escapeall # 允许使用反斜杠（pymdownx 支持，mkdocs 貌似部分支持，不完全支持）
  - pymdownx.magiclink # 自动识别超链接（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.progressbar # 允许进度条语法（pymdownx 支持，mkdocs 暂时不支持）
  - pymdownx.saneheaders # “#title” 也是标题，虽然中间没有空格（pymdownx 支持，mkdocs 暂时不支持）

  - pymdownx.blocks.tab # 支持更高级的标签块写法（危：可能与 pymdownx.tabbed 冲突）
  - pymdownx.blocks.html # 支持一些更高级的 md 内嵌 HTML 语法（pymdownx.blocks 默认开启）
  - pymdownx.blocks.details # 支持更高级的提示框布局（危：可能与 pymdownx.details 冲突）
  - pymdownx.blocks.admonition # 支持更高级提示框语法（危：可能与 admonition 冲突）
  - pymdownx.blocks.definition # 支持更高级的定义块语法（危：可能与 def_list）

  - pymdownx.arithmatex: # 允许数学表达式，即 $$y=x+1$$，或行内的 $x=1$
      generic: true

  - pymdownx.betterem: # 允许斜体和加粗
      smart_enable: all

  - pymdownx.critic: # 允许批注，批注详情见 https://mkdoc-material.llango.com/reference/formatting/
      mode: view # 批注模式，可为 view，accept 和 reject，不懂干啥的

  - pymdownx.highlight: # 允许代码块语法高亮
      use_pygments: true # 使用 pygments 而不是 javascript，啥意思不懂
      linenums: true # 全部显示行号，若为 false，也可指定起始行号，如 ```python linenums="2"，也可指定高亮行，如 hl_lines="2-3"
      linenums_style: pymdownx-inline # 行号样式 pymdownx-inline 或者 inline 和 table（最好不要使用其它的值，会有 bug，如代码复制按钮错位）
      anchor_linenums: true # 用锚链接包装代码行号，便于超链接和共享（就是行号可以像锚点一样被点击）
      line_spans: __span # 这对于行突出显示等功能正常工作至关重要，不懂
      pygments_lang_class: true # 对于自定义注释标记的功能至关重要，不懂
      # auto_title: true # 自动为所有代码块添加一个标题

  - pymdownx.emoji: # 允许 Emoji 表情
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.superfences: # 允许各种嵌套
      custom_fences:
        - name: mermaid # 允许 mermaid 图表语法
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # 不清楚干啥的


  - pymdownx.tabbed: # 允许块（如代码块）添加标签，实现多语言等效果
      alternate_style: true # 唯一支持的样式，不打开等于用不了
      combine_header_slug: true # 后面的不知道干啥的
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

  - pymdownx.tasklist: # 允许 Todo 列表清单
      custom_checkbox: true # 允许修改其样式，不然用默认样式就很丑
      clickable_checkbox: true # 是否可通过点击切换状态（但无实际更改，只有视觉效果）

  # === 从这里开始到下面，是 Python-Markdown（MkDocs 默认的） 的 markdown_extensions 配置 ===

  - meta # 允许元标记，页面源代码顶上那几行被横线保住的内容就是元标记，为了支持某些功能使用
  - abbr # 允许文本悬浮提示，就是 ToolTip，例如：*[Text]: 啊吧啊吧
  - tables # 允许用简单语法创建表格
  - smarty # 貌似是为了提高兼容性的，不太清楚
  - def_list # 允许“定义列表”的语法，详细见 https://mkdoc-material.llango.com/reference/lists/
  - attr_list # 允许给 md 元素增加 HTML 和 CSS 属性，如一个按钮 [Subscribe to our mailing list](#){: .md-button }，甚至图标，详细见 https://mkdoc-material.llango.com/reference/buttons/
  - wikilinks # 支持快捷链接语法，例如 [[a link]]，会变成 ./a_link/
  - admonition # 允许各种各样的提示框，或代码框，样式见 https://mkdoc-material.llango.com/reference/admonitions/
  - md_in_html # 允许 md 内嵌在 HTML 中
  - sane_lists # 理智列表，避免旧版 md 抽风（强烈推荐开启）
  # - nl2br # 换行符硬断裂，即文本不像旧版 md 那样，可以直接换行
  # - codehilite # 被 pymdownx 相关扩展取代了，不建议使用这个
  # - fenced_code # 被 pymdownx 相关扩展取代了，不建议使用这个

  - footnotes: # 允许脚注
      BACKLINK_TITLE: 返回脚注 {} # 底部脚注的提示词，建议改一下，默认是英文的
      # SUPERSCRIPT_TEXT: {} # 脚注名称，默认就是 {}，表示标号

  - toc: # 目录设置
      title: 目录 # 在右侧导航侧边栏中设置目录的标题
      permalink_title: 点击定位到锚点 # 设置锚点链接的提示词
      permalink: "#" # 启用目录锚点，并设置符号为 “#”
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify # 这啥玩意儿，不懂，抄官网的
        kwds:
          case: lower

theme: # 主题设置
  name: material # 第三方主题名称
  #custom_dir: docs/overrides # 覆盖部分原来的主题（重载目录）
  language: zh # material 语言

  features:
    - header.autohide # 顶栏自动隐藏
    - content.tooltips # 提示框（以前有的样式变好看了，此外还支持更高级的提示框语法）
    - content.code.copy # 例如：``` python { .yaml .copy } 默认开启，{ .yaml .no-copy } 关闭
    - content.code.annotate # 允许内联代码注释
    - content.tabs.link # 同样的标签，整个网站的同步切换，如 C -> C++，则其它类似的全部标签都同步切换
    - announce.dismiss # 公告栏可以被关闭
    # - navigation.expand # 左侧边栏节点默认全部展开（与 navigation.prune 不兼容）
    # - navigation.prune # 左侧栏节点至多展开一个，以此来减小站点的构建大小（对于页数100+的网站很有用，但是！与 navigation.expand 不兼容）
    - navigation.tabs # 页面顶部导航栏
    - navigation.tabs.tags # 在顶部导航栏显示标签索引页面
    - navigation.footer # 页面底下换页的支持
    - navigation.indexes # 左侧边栏大节点是否可以被导向到 index.md
    # - navigation.instant # 页面不会重复加载（已加载页面不会再次加载）
    - navigation.instant.progress # 加载速度慢时，在页面顶部显示加载进度（400ms 以上加载时间才会显示它）
    # - navigation.tabs.sticky # 导航栏标题栏位置固定
    # - navigation.sections # 左侧边栏节点是否保持展开
    - navigation.top # 回到顶部的按钮
    - navigation.tracking # 锚点跟踪
    - search.share # 搜索栏分享按钮
    - search.suggest # 搜索栏内容建议
    - search.highlight # 搜索栏内容高亮
    - toc.follow # 锚点关注，侧边栏自动滚动，使锚点总是可见
    # - toc.integrate # 右边侧栏是否集成到左侧边栏

  palette: # 界面整体样式
    - media: "(prefers-color-scheme)" # 系统主题
      toggle: # 切换按钮
        icon: material/theme-light-dark # 图标
        name: 切换至明亮主题 # 提示词
    - media: "(prefers-color-scheme: light)" # 亮色主题
      scheme: default
      #primary: blue # 标题栏颜色（建议自定义 CSS 调整，因为 footer 不会被此参数影响！）
      accent: purple # 链接高亮颜色
      toggle:
        icon: material/weather-sunny
        name: 切换至暗黑主题
    - media: "(prefers-color-scheme: dark)" # 暗色主题
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/weather-night
        name: 切换至系统主题
  font: false # 避免从谷歌加载字体导致网页加载变慢
  logo: logo.png # 页面左上角徽标
  favicon: logo.png # 网页的图标
  icon: # 图标重载，替换掉默认的图标
    previous: fontawesome/solid/angle-left # 左下角向前翻页的图标
    next: fontawesome/solid/angle-right # 右下角向后翻页的图标
    # repo: fontawesome/brands/github # 右上角仓库图标
extra: # 额外设定
  homepage: . # 左上角徽标链接的地址（此处为一个点，也就是主页）
  social: # 联系方式（页面右下角内容）
    - icon: fontawesome/brands/github # 图标（可以去官网看有哪些）
      link: https://ZJUCSSU.github.io/home/ # 链接
      name: GitHub 仓库 # 提示词
    - icon: fontawesome/solid/house
      link: https://github.com/ZJUCSSU/home/
      name: 主页
    - icon: fontawesome/solid/paper-plane
      link: mailto:1744523875@qq.com
      name: 联系作者

extra_javascript: # 额外 JS
  - javascripts/extra.js
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
# extra_css: # 额外 CSS
#   - stylesheets/extra.css
#   - stylesheets/table.css
#   - https://cdn.bootcss.com/font-awesome/4.3.0/css/font-awesome.min.css # 访问统计转圈加载样式
#   - CSS/admonition.css
#   - CSS/other.css
#   - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

plugins:
#  - callouts # 支持 obsidian-like callout 语法，例如：```> [!note] title \n> content...```
  - macros # 本地pip install mkdocs-macros-plugin 安装插件
  - tags
  - search:
      separator: '[\s\u200b\-]' # 支持中文搜素
# plugins: # 插件
#   - git-revision-date-localized: # 文章日期显示插件（pip install mkdocs-git-revision-date-localized-plugin）注意：build 时此插件加载非常缓慢！
#       enable_creation_date: true # 显示创建的日期
#       type: datetime # 每页底下显示最后更新日期，类型是 datatime（日期+时间），或者 data（只有日期）等
#       locale: zh # 换成中文显示
#   - git-authors: # 文章作者显示插件（pip install mkdocs-git-authors-plugin）注意：build 时此插件加载非常缓慢！
#       show_contribution: true # 显示贡献比例
#       show_line_count: true # 记录行数
#       show_email_address: true # 显示邮箱
#       count_empty_lines: false # 记录空行的贡献
#       fallback_to_empty: false # 不懂
#       sort_authors_by: contribution # 贡献者名单排序方式 (name, contribution)
#       authorship_threshold_percent: 0 # 筛选掉贡献比例低于该百分比的贡献者
#   - glightbox: # 图像缩放插件（pip install mkdocs-glightbox）
#       touchNavigation: true # 启用或禁用触摸导航（轻扫），应该是便于手机用户吧
#       loop: false # 换图时循环
#       effect: zoom # 打开图时的效果(zoom, fade, none)
#       slide_effect: slide # 切换图片时的效果(slide, zoom, fade, none)
#       width: auto # 内联元素和 iframe 的宽度。您可以使用任何单位或者 auto
#       height: auto # 同上
#       zoomable: false # 启用或禁用可缩放图像，不懂干啥的
#       draggable: true # 启用或禁用鼠标拖动以转到上一张和下一张图片
#       auto_caption: false # 自动启用或禁用使用图像的替代文本作为标题
#       caption_position: bottom # 标题位置 (bottom, top, left, right)
#       background: none # 背景颜色
#       shadow: true # 启用或禁用图像阴影
#   - changelog # 日志插件（pip install mkdocs-changelog-plugin）
#   - statistics: # 数据统计插件（pip install mkdocs-statistics-plugin）
#       codelines_per_minute: 15 # 每分钟可看的代码行数
#       words_per_minute: 150 # 每分钟可看的文本数
#   - minify: # 压缩文件的插件（pip install mkdocs-minify-plugin）
#       minify_html: true
#       minify_js: true
#       minify_css: true
#       htmlmin_opts:
#         remove_comments: true
#       cache_safe: true

nav:
  - 主页: index.md
  - 通知中心:
      - 教学事务:
          - 选课补退选通知: Notification/教学事务/选课补退选通知.md
          - 培养计划与学分要求: Notification/教学事务/培养计划与学分要求.md
          - 毕业设计/论文相关: Notification/教学事务/毕设论文.md
      - 就业发展:
          - 实习招聘信息: Notification/就业发展/实习招聘.md
          - 校园招聘会: Notification/就业发展/校园招聘会.md
          - 企业宣讲会: Notification/就业发展/企业宣讲会.md
          - 就业指导与培训: Notification/就业发展/就业指导与培训.md
          - 选调生/公务员招录: Notification/就业发展/选调生公务员招录.md
          - 专项计划: Notification/就业发展/专项计划.md
          - 1+2 / 2+2 项目信息: Notification/就业发展/项目信息.md
      - 科研动态:
          - 科研项目/课题组招募: Notification/科研动态/课题组招募.md
          - 学术竞赛通知: Notification/科研动态/学术竞赛通知.md
          - 学术讲座与沙龙预告: Notification/科研动态/学术讲座与沙龙预告.md
          - 学术会议信息: Notification/科研动态/学术会议信息.md
      - 对外交流:
          - 公派/交换项目: Notification/对外交流/公派交换项目.md
          - 寒暑期学校与项目: Notification/对外交流/寒暑期学校与项目.md
          - 国际会议与活动: Notification/对外交流/国际会议与活动.md
      - 评奖评优与资助:
          - 奖学金评定: Notification/评奖评优与资助/奖学金评定.md
          - 荣誉称号评选: Notification/评奖评优与资助/荣誉称号评选.md
          - 助学金与困难补助: Notification/评奖评优与资助/助学金与困难补助.md
          - 助学贷款与学费减免: Notification/评奖评优与资助/助学贷款与学费减免.md
          - 勤工助学岗位: Notification/评奖评优与资助/勤工助学岗位.md
      - 文体活动:
          - 校园文化活动: Notification/文体活动/校园文化活动.md
          - 体育赛事与校运会: Notification/文体活动/体育赛事与校运会.md
          - 美育二课机会: Notification/文体活动/美育二课机会.md
          - 社团俱乐部纳新与活动: Notification/文体活动/社团俱乐部纳新与活动.md
          - 文体讲座与座谈: Notification/文体活动/文体讲座与座谈.md
      - 校园综合信息:
          - 节假日安排: Notification/校园综合信息/节假日安排.md
          - 后勤服务: Notification/校园综合信息/后勤服务.md
          - 失物招领: Notification/校园综合信息/失物招领.md
          - 安全教育与提醒: Notification/校园综合信息/安全教育与提醒.md
      - 思想成长:
          - 形策课程安排: Notification/思想成长/形策课程安排.md
          - 理论学习通知: Notification/思想成长/理论学习通知.md
          - 心理健康讲座与活动: Notification/思想成长/心理健康讲座与活动.md
          - 志愿者招募: Notification/思想成长/志愿者招募.md
  - 意见反馈:
      - 如何提交ISSUE: 意见反馈/ISSUE.md
      - 吐槽回应: 意见反馈/吐槽回应.md
      - 通知答疑: 意见反馈/通知答疑.md
      - 匿名反馈: 意见反馈/匿名反馈.md
  - 知识共享:
      - 培养方案:
          - 计算机科学与技术: 知识共享/培养方案/CS/cs_site.md
          - 软件工程: 知识共享/培养方案/软件工程/se_site.md
          - 信息安全: 知识共享/培养方案/信息安全/is_site.md
          - 工业设计: 知识共享/培养方案/工业设计/id_site.md
          - 人工智能: 知识共享/培养方案/人工智能/ai.md
          - 通识课程: 知识共享/培养方案/general/general_courses.md
          - 跨专业课程: 知识共享/培养方案/general/cross_majors.md
      - 课程学习: 知识共享/课程笔记/example.md
      - 课外学习: 知识共享/课外学习/example.md
  - 资源分享:
      - 个人笔记:
          - 笔记说明: 资源分享/个人笔记/example.md
      - 个人项目: 资源分享/个人项目/example.md
